# fly.toml app configuration file generated for dennis on 2023-06-14T18:08:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dennis"
primary_region = "mia"

[[services]]
  internal_port = 6379
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [[services.ports]]
    port = 6379
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20


